name: Whatsapp box (dialog flow bot to whatsapp) CI

on:
  pull_request:
    branches: [ master, staging ]
  push: 
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Run eslint
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: lint
      - name: Run mocha and chai test
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - name: Run clean path
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: clean